import Vue from "vue";
import { Aside, Button, Card, Checkbox, Container, Dialog, Divider, Dropdown, DropdownItem, DropdownMenu, Footer, Form, FormItem, Header, Input, Main, Popover, Radio, RadioGroup, Table, TableColumn, Tree, Upload, Tabs, TabPane, Slider, Select, Option, ColorPicker } from "element-ui";

Vue.use(Aside);
Vue.use(Button);
Vue.use(Card);
Vue.use(Checkbox);
Vue.use(ColorPicker);
Vue.use(Container);
Vue.use(Dialog);
Vue.use(Divider);
Vue.use(Dropdown);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Footer);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Header);
Vue.use(Input);
Vue.use(Main);
Vue.use(Popover);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(Tree);
Vue.use(Upload);
Vue.use(Tabs);
Vue.use(TabPane);
Vue.use(Slider);
Vue.use(Select);
Vue.use(Option);
